# Generated by Django 3.1.3 on 2020-11-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
